%Variables initiales (modifiables)
INIT_NIV_BAT = 50;
TIME_TO_CHARGE_M = 50;
VITESSE_MAX_MS = 0.5;
BAT_AUTONOMY_H = 20;

INIT_POS_X = 0;
INIT_POS_Y = 0;
INIT_POS_Z = 0;

INIT_APLHA = 0;
INIT_THETA = 0;
INIT_VITESSE = 0;


INIT_FOND_MARIN = -1000;
VARIANCE_INCL_FOND = 25;

TIME_PHOTO_S = 4;
TIME_APPEL_CHARGE_M = 60;
TIME_TRANSM_S = 10;
PHOTO_FAIL_RATE = 1;

SIMU_ACCEL = 10;

%Variables calculées à partir des précédentes (non modifiables)
TIME_TO_CHARGE_S = TIME_TO_CHARGE_M*60;
BAT_AUTONOMY_S = BAT_AUTONOMY_H * 3600;
TIME_APPEL_CHARGE_S = TIME_APPEL_CHARGE_M * 60;